version: '3'

services:
  tools:
    build:
      context: ./tools
      dockerfile: ./Dockerfile
    links:
      - postgres
    volumes:
      - ./mnt:/mnt
      - ./mnt/dem:/mnt/dem
      - ./tools/scripts:/scripts
    tty: true

  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_PASSWORD=render
      - POSTGRES_USER=render
      - POSTGRES_DB=renderdb
    volumes:
      - ./mnt:/mnt
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - ./postgres/scripts:/scripts
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql.conf
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - 5432:5432

  # tileserver:
  #   build:
  #     context: ./tileserver
  #     dockerfile: ./Dockerfile
  #   links:
  #     - postgres
  #   ports:
  #     - 80:80
  #   tty: true
  #   volumes:
  #     - ./mnt:/mnt
  #     - ./tiles:/var/lib/mod_tile
  #     - ./tileserver/configs/renderd.conf:/usr/local/etc/renderd.conf
  #     - ./tileserver/configs/mod_tile.conf:/etc/apache2/conf-enabled/mod_tile.conf
  #     - ./www:/var/www/html
  #     - ./tileserver/scripts:/scripts

