version: '3'

services:
  tools:
    build:
      context: ./tools
      dockerfile: ./Dockerfile
    links:
      - postgres
    volumes:
      - ./mnt:/mnt
      - ./tiles:/tiles
      - ./www:/www
      - ./mnt/dem:/mnt/dem
      - ./tools/web_server:/web_server
      - ./tools/scripts:/scripts
    tty: true
    ports:
      - 5000:5000

  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_PASSWORD=render
      - POSTGRES_USER=render
      - POSTGRES_DB=renderdb
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql.conf
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - 5432:5432
    stop_grace_period: 120s

